server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer1
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

cors:
 allowed-origins: "*"
 allowed-methods: "*"
 allowed-headers: "*"
 exposed-headers: "*"

management:
  endpoints:
    web:
      exposure:
        exclude: "health,info"
