name: CD - Deploy React Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - frontend/react/**


jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/react
    steps:
      - uses: actions/checkout@v3
      - name: Set build number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_OUTPUT
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: name/app:latest, name/app:${{steps.build-number.outputs.BUILD_NUMBER}}
      - name: Send Message TG
        run: >
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendMessage
          -d text="Front has been updated, with job status: ${{ job.status }}: https://github.com/nikitosik-761/MyApp/commit/${{ github.sha }} - ${{ github.event.head_commit.message }} 🎉"
          -d chat_id=${{ secrets.TG_CHAT }}

